trigger:
  branches:
    include:
      - main  # This can be any branch you'd like to trigger the pipeline on

pr: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: CreateBugInAzureDevOps
    displayName: "Create Bug in Azure DevOps"
    steps:
      - task: Bash@3
        displayName: "Extract GitHub Issue Details and Create Bug in Azure Boards"
        inputs:
          targetType: 'inline'
          script: |
            # Example: GitHub issue details passed as environment variables
            issue_title="GitHub Issue: $(Build.SourceBranchName)"
            issue_body="Issue details for $(Build.SourceBranchName)"

            # Create Bug Task in Azure DevOps using REST API
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $(AZURE_DEVOPS_PAT)" \
              -d '{
                    "fields": {
                      "System.Title": "'"$issue_title"'",
                      "System.Description": "'"$issue_body"'",
                      "System.WorkItemType": "Bug"
                    }
                  }' \
              https://dev.azure.com/DevOps1290/SAFe_Support_POC/_apis/wit/workitems/\$Bug?api-version=6.0
