trigger:
  branches:
    include:
      - main  # or the branch where you want the trigger

pr: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: issueTitle
    displayName: Issue Title
    type: string
    default: ''

# This pipeline will only run when issues are created in GitHub
resources:
  repositories:
    - repository: self
      type: github
      name: Hariprasad29kc/Sampl_1
      endpoint: SAFe_Support_POC

jobs:
  - job: CreateBugInAzureDevOps
    displayName: "Create Bug in Azure DevOps"
    steps:
      - task: Bash@3
        displayName: "Create a Bug Task in Azure DevOps"
        inputs:
          targetType: 'inline'
          script: |
            # Extract GitHub issue details
            issue_title=$(curl -H "Authorization: token $(System.AccessToken)" \
                            https://api.github.com/repos/Hariprasad29kc/Sampl_1/issues/$(github.issue.number) \
                            | jq -r .title)

            issue_body=$(curl -H "Authorization: token $(System.AccessToken)" \
                            https://api.github.com/repos/Hariprasad29kc/Sampl_1/issues/$(github.issue.number) \
                            | jq -r .body)

            # Create Bug Task in Azure DevOps using REST API
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $(AZURE_DEVOPS_PAT)" \
              -d '{
                    "fields": {
                      "System.Title": "'$issue_title'",
                      "System.Description": "'$issue_body'",
                      "System.WorkItemType": "Bug"
                    }
                  }' \
              https://dev.azure.com/DevOps1290/SAFe_Support_POC/_apis/wit/workitems/$Bug?api-version=6.0
  


