trigger: none   # No branch triggers

pr: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: CreateBugInAzureDevOps
    displayName: "Create Bug in Azure DevOps"
    steps:
      - task: Bash@3
        displayName: "Extract GitHub Issue Details and Create Bug in Azure Boards"
        inputs:
          targetType: 'inline'
          script: |
            # Example: GitHub issue details passed as environment variables
            issue_title="GitHub Issue: $(Build.SourceBranchName)"
            issue_body="Issue details for $(Build.SourceBranchName)"

            # Create Bug Task in Azure DevOps using REST API
            curl -u :$(AZURE_DEVOPS_PAT) \
              -X POST \
              -H "Content-Type: application/json-patch+json" \
              -d '[{
                    "op": "add",
                    "path": "/fields/System.Title",
                    "value": "'"$issue_title"'"
                  },
                  {
                    "op": "add",
                    "path": "/fields/System.Description",
                    "value": "'"$issue_body"'"
                  },
                  {
                    "op": "add",
                    "path": "/fields/System.WorkItemType",
                    "value": "Bug"
                  }]' \
              https://dev.azure.com/DevOps1290/SAFe_Support_POC/_apis/wit/workitems/\$Bug?api-version=7.0
