trigger:
  branches:
    include:
      - main  # or the branch where you want the trigger

pr: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: issueTitle
    displayName: Issue Title
    type: string
    default: ''

# This pipeline will only run when issues are created in GitHub
resources:
  repositories:
    - repository: self
      type: github
      name: Hariprasad29kc/Sampl_1
      endpoint: SAFe_Support_POC

jobs:
  - job: CreateBugInAzureDevOps
    displayName: "Create Bug in Azure DevOps"
    steps:
      - task: Bash@3
        displayName: "Create a Bug Task in Azure DevOps"
        inputs:
          targetType: 'inline'
          script: |
            echo "Creating a bug in Azure DevOps..."

            # Use curl to call the Azure DevOps REST API and create a bug
            curl -u :$(AZURE_DEVOPS_PAT) \
            -X POST \
            -H "Content-Type: application/json-patch+json" \
            -d '[{ "op": "add", "path": "/fields/System.Title", "value": "Bug created from commit" }]' \
            https://dev.azure.com/DevOps1290/SAFe_Support_POC/_apis/wit/workitems/\$Bug?api-version=7.0
  


